import { getServerSession } from "next-auth/next";
import { authOptions } from "../api/auth/[...nextauth]";
import Head from "next/head";
import { IoBed, IoFlash, IoFootsteps, IoHome, IoImages, IoPieChart, IoSave, IoText, IoWallet } from "react-icons/io5";
import Body from "../../components/Body/Body";
import NavbarMenuItem from "../../components/navbar/NavbarMenuItem/NavbarMenuItem";
import NavbarStats from "../../components/Stats/Stats";
import getRole from "../../lib/utils/getRole";
import Role from "../../lib/utils/roles";
import { useSession } from "next-auth/react";
import InputLayout from "../../components/layouts/InputLayout/InputLayout";
import Tile from "../../components/Tile/Tile";
import { TileType } from "../../components/Tile/Tile";
import Button from "../../components/Button/Button";
import InstructionsLayout from "../../components/layouts/InstructionsLayout/InstructionsLayout";
import HomeForm from "../../components/forms/HomeForm/HomeForm";

const navItems = [
    <NavbarMenuItem key={"allhomes-link"} icon={<IoHome />} text="All Homes" onClick={() => console.log("AllHomes")} activePage={false} />,
    <NavbarMenuItem
        key={"dashboard-link"}
        icon={<IoPieChart />}
        text="Dashboard"
        onClick={() => console.log("Dashboard")}
        activePage={true}
    />,
];

const statItems = [
    <NavbarStats key={"somestats-stats"} stat="30" text="some stats (testing)" />,
    <NavbarStats key={"cost-stats"} stat="£4.50" text="cost" />,
    <NavbarStats key={"cool-stats"} stat="60" text="some more stats (that are cool)" />,
];

export default function NewHome(props) {
    const {userSession} = props;

    return (
        <>
            <Head>
                <title>New Home</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Body menuItems={navItems} statItems={statItems} session={userSession}>
                <h1 className="mx-6 mb-4 text-3xl col-span-1 md:col-span-2">New Home</h1>

                <div className="mx-6 my-2">
                    <HomeForm/>
                </div>
            </Body>
        </>
    );
}

export async function getServerSideProps(context) {
    const session = await getServerSession(context.req, context.res, authOptions);
    const role = getRole(session);

    if (role !== Role.Agency) {
        return {
            redirect: {
                destination: "/",
                permanent: false,
            },
        };
    }

    return {
        props: {
            userSession: session,
        },
    };
}
