import NavbarMenuItem from "../../../components/navbar/NavbarMenuItem/NavbarMenuItem";
import NavbarStats from "../../../components/Stats/Stats";
import {IoHome, IoPieChart, IoFlash, IoList, IoLogOut} from "react-icons/io5";
import Body from "../../../components/Body/Body";
import Head from "next/head";
import { useRouter } from "next/router";

// TO DO - UPDATE LINKS

export default function test() {
    const router = useRouter();

    const navItems = [
        <NavbarMenuItem
                        icon={<IoHome />}
                        text="All Homes"
                        onClick={() => router.push(`/`)}
                        activePage={false} 
                    />,
        <NavbarMenuItem
                    icon={<IoPieChart />}
                    text="Dashboard"
                    onClick={() => router.push(`/`)}
                    activePage={true} 
        />,
        <NavbarMenuItem
                    icon={<IoFlash />}
                    text="New Reading"
                    onClick={() => router.push(`/`)}
                    activePage={false} 
        />,
        <NavbarMenuItem
                    icon={<IoList />}
                    text="Instructions"
                    onClick={() => router.push(`/`)}
                    activePage={false} 
        />,
        <NavbarMenuItem
                    icon={<IoLogOut />}
                    text="Sign Out"
                    onClick={() => router.push(`/`)}
                    activePage={false} 
        />]

    const statItems = [
        <NavbarStats stat="30" text="some stats (testing)" />,
        <NavbarStats stat="£4.50" text="cost"/>,
        <NavbarStats stat="60" text="some more stats (that are cool)"/>
    ]


    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Body menuItems={navItems} statItems={statItems}>
                <p>The Body</p>
            </Body>
        </>
        



       
    )
}